# Generated by Django 4.2.5 on 2023-11-20 15:20

import apps.usuario.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiDo_Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiGe_Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Username', models.CharField(max_length=250)),
                ('User_Password', models.CharField(max_length=250)),
                ('User_Avatar', models.ImageField(upload_to=apps.usuario.models.archivo_upload_path)),
                ('User_Nombres', models.CharField(max_length=250)),
                ('User_Apellidos', models.CharField(max_length=250)),
                ('User_Correo', models.CharField(max_length=250)),
                ('User_Documento', models.CharField(max_length=45)),
                ('Tipo_Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipo_documento')),
                ('Tipo_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipo_genero')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioxLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicenciaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.licencia_clase')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
