# Generated by Django 4.2.5 on 2023-11-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0003_alter_rolxusuario_usuarioid'),
        ('usuario', '0004_remove_usuario_tipo_documento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
