# Generated by Django 4.2.5 on 2023-11-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuarios_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$FrgMes1T9wbuR78gKwNTcH$CNc01p52Bjz2SZkla5uhIylgDL0lEx4LUV62I0aGtaQ=', max_length=128),
        ),
    ]
