# Generated by Django 4.2.5 on 2023-11-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recu_Titulo', models.CharField(max_length=250)),
                ('Recu_Path', models.CharField(max_length=250)),
                ('Recu_Padre', models.CharField(max_length=250)),
                ('Recu_Icono', models.CharField(max_length=250)),
                ('Recu_Link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol_Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RolxUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.rol')),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RecursosxRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecursosID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.recursos')),
                ('RolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.rol')),
            ],
        ),
    ]
