# Generated by Django 4.2.5 on 2023-11-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curs_Nombre', models.CharField(max_length=250)),
                ('Curs_Cupos', models.IntegerField()),
                ('Curs_Cupos_Disponibles', models.IntegerField()),
                ('Curs_Dias_Uso', models.IntegerField()),
                ('Curs_Dias_Garantia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nive_Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiac_nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tico_Nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unid_Nombre', models.CharField(max_length=250)),
                ('NivelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia_clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lice_Nombre', models.CharField(max_length=250)),
                ('Lice_Cupo', models.CharField(max_length=250)),
                ('Lice_Fecha_inicio', models.DateField()),
                ('Lice_Fecha_fin', models.DateField()),
                ('CursoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leci_Nombre', models.CharField(max_length=250)),
                ('Leci_Descripcion', models.TextField()),
                ('Leci_Contenido', models.IntegerField()),
                ('Leci_Actividades', models.IntegerField()),
                ('Leci_Examen', models.IntegerField()),
                ('TiacID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.tipo_actividad')),
                ('TicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.tipo_contenido')),
            ],
        ),
        migrations.CreateModel(
            name='CursoxNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('NivelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.nivel')),
            ],
        ),
    ]
