# Generated by Django 4.2.5 on 2023-11-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoxnivel',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoxnivel',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='licencia_clase',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='licencia_clase',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_actividad',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_actividad',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_contenido',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_contenido',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='updateAt',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
